### PR TITLE
Fix a compatibility issue with .NET 6

### PR DESCRIPTION
**Pull request by Baune8D**

### CODE REVIEW

**Comment by mysticmind** [comment]
@Baune8D We are not doing any more fixes or releases on 3.x and suggesting users to migrate the latest 5.x which is fully tested with .NET 6. 

That said, let me check with @jeremydmiller on this and keep you posted.

**Comment by Baune8D** [comment]
> @Baune8D We are not doing any more fixes or releases on 3.x and suggesting users to migrate the latest 5.x which is fully tested with .NET 6.
> 
> That said, let me check with @jeremydmiller on this and keep you posted.

At my work we have a lot of microservices that currently rely on Marten v3. It's a really big undertaking for us to migrate everything to v4, and right now v3 is blocking us from moving on to .NET 6.

Would really appreciate this PR being pulled in if possible 🙂

**Comment by mysticmind** [comment]
@Baune8D understood, we will take your situation into consideration and do the needful.

**Review by mysticmind — APPROVED** [review]
Changes look good to me!

**Comment by mysticmind** [comment]
@Baune8D I will do a release in sometime.

**Comment by mysticmind** [comment]
I have released 3.14.3, release notes are [here](https://github.com/JasperFx/marten/releases/tag/3.14.3)

**Pull request merged**
