### PR TITLE
Added support for compiled queries with include for lists & dictionaries

### LINKED ISSUE #358: Support compiled query with Include() for lists and dictionaries
This currently fails:
``` chsarp
        public class IssueWithUsers : ICompiledQuery<Issue,IMartenQueryable<Issue>>
        {
            public List<User> Users { get; set; }
            public Expression<Func<IQueryable<Issue>, IMartenQueryable<Issue>>> QueryIs()
            {
                return query => query.Include<Issue, IssueWithUsers>(x => x.AssigneeId, x => x.Users, JoinType.Inner);
            }
        }

        [Fact]
        public void compiled_include_to_list()
        {
            var user1 = new User();
            var user2 = new User();

            var issue1 = new Issue { AssigneeId = user1.Id, Title = "Garage Door is busted" };
            var issue2 = new Issue { AssigneeId = user2.Id, Title = "Garage Door is busted" };
            var issue3 = new Issue { AssigneeId = user2.Id, Title = "Garage Door is busted" };

            theSession.Store(user1, user2);
            theSession.Store(issue1, issue2, issue3);
            theSession.SaveChanges();

            using (var session = theStore.QuerySession())
            {
                var query = new IssueWithUsers();

                var issues = session.Query(query).ToArray();

                query.Users.Count.ShouldBe(2);
                issues.Count().ShouldBe(3);

                query.Users.Any(x => x.Id == user1.Id);
                query.Users.Any(x => x.Id == user2.Id);
            }
        }
```

### PR DESCRIPTION
**Pull request by nieve**
Closes #358

### CODE REVIEW

**Comment by nieve** [comment]
Will add docs for it later on today/tomorrow.

**Comment by jeremydmiller** [comment]
@nieve would you want me to pull this in now, or wait for the docs? I'm not in any huge hurry to kick out a new nuget, so no rush.

**Comment by nieve** [comment]
Done :)

**Comment by jeremydmiller** [comment]
Got it w/ a rebase, thanks @nieve !

**Pull request closed without merging**
