### PR TITLE
Reinstate previous function versions in patch rollback DDL

### LINKED ISSUE #1205: Patch DDL rollback script doesn't recreate previous document functions
We're managing our db schema externally from our application, using AutoCreate.None, and generating sql migration files using Marten.CommandLine.
When generating a patch for adding a duplicate field or some other operation which requires a new set of upsert/insert/update functions, to patch dll correctly removes the old functions and creates the new function definitions.
But the rollback patch dll removes the newly created functions, but doesn't recreate the previous set of functions. Therefore the database after rollback is not in a usable format when using AutoCreate.None, as Marten can not recreate the functions.

Ideally i think the patch engine would grab the previous function definitions from the database and include them in the rollback DDL so the patch rollback is a complete inverse.

Does this sound sensible to you? If so I'm happy to get stuck in and see if i can come up with an implementation.

### PR DESCRIPTION
**Pull request by richardoliver-umusic**
Fixes #1205

### CODE REVIEW

**Comment by richardoliver-umusic** [comment]
The CI failure is the following which i don't believe should have been affected/caused by my change. Is this a common failure?
```
[xUnit.net 00:02:42.5299312]     Marten.Testing.Linq.query_with_dates_Tests.can_select_DateTimeOffset_and_will_return_localtime [FAIL]
Failed   Marten.Testing.Linq.query_with_dates_Tests.can_select_DateTimeOffset_and_will_return_localtime
Error Message:
 Shouldly.ShouldAssertException : 3/5/2019 5:16:32 PM +00:00
    should be
3/5/2019 5:16:32 PM +00:00
    but was not
Stack Trace:
   at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected)
   at Marten.Testing.SpecificationExtensions.ShouldBeEqualWithDbPrecision(DateTimeOffset actual, DateTimeOffset expected) in C:\projects\marten\src\Marten.Testing\SpecificationExtensions.cs:line 211
   at Marten.Testing.Linq.query_with_dates_Tests.can_select_DateTimeOffset_and_will_return_localtime() in C:\projects\marten\src\Marten.Testing\Linq\query_with_dates_Tests.cs:line 28
```

**Comment by mysticmind** [comment]
@richardoliver-umusic there are few known blinking tests. I will re-run the failed AppVeyor CI build.

**Comment by richardoliver-umusic** [comment]
Cheers @mysticmind

**Comment by jeremydmiller** [comment]
Good from my side too

**Pull request merged**
