### PR TITLE
Reproduction for events being applied out of sequence when rebuilding a MultiStreamAggregation

### PR DESCRIPTION
**Pull request by T0shik**

### CODE REVIEW

**Comment by mysticmind** [comment]
To solve your issue of events ordered by sequence, create a custom slicer as below:
```csharp
public class CustomSlicer: IEventSlicer<Projection, Guid>
{
    public ValueTask<IReadOnlyList<EventSlice<Projection, Guid>>> SliceInlineActions(
        IQuerySession querySession, IEnumerable<StreamAction> streams)
    {
        var events = streams.SelectMany(x => x.Events).ToList();
        var group = new TenantSliceGroup<Projection, Guid>(Tenant.ForDatabase(querySession.Database));
        group.AddEvents<ICommonId>(@event => @event.Id, events);

        return new(group.Slices.ToList());
    }

    public ValueTask<IReadOnlyList<TenantSliceGroup<Projection, Guid>>> SliceAsyncEvents(
        IQuerySession querySession, List<IEvent> events)
    {
        var group = new TenantSliceGroup<Projection, Guid>(Tenant.ForDatabase(querySession.Database));
        group.AddEvents<ICommonId>(@event => @event.Id, events);

        return new(new List<TenantSliceGroup<Projection, Guid>>{group});
    }
}
```

In the `Projector` ctor, use the custom slicer `CustomGrouping(new CustomSlicer());` instead of `Identity<Happened>(x => x.Id);`

**Comment by mysticmind** [comment]
Quick follow on note, I do acknowledge that the sequence of events is out of order using the default slicer when using async daemon. I have identified the code https://github.com/JasperFx/marten/blob/b942cb89abf07c09191b857203e5e7c262b13016/src/Marten/Events/Aggregation/EventSlice.cs#L125 which is causing this, will add a fix to order by sequence followed by version i.e. change `var events = _events.Distinct().OrderBy(x => x.Version).ToArray();` to `var events = _events.Distinct().OrderBy(x => x.Sequence).ThenBy(x => x.Version).ToArray();`

**Comment by T0shik** [comment]
Thank you

just my 2 cents as I don't know how things are done around this project. 

people might have logic depending on 
`var events = _events.Distinct().OrderBy(x => x.Version).ToArray();`

changing that could fix things for me but break for others, perhaps a config property that enables a switch to 
`var events = _events.Distinct().OrderBy(x => x.Sequence).ThenBy(x => x.Version).ToArray();`

**Comment by jeremydmiller** [comment]
@mysticmind Ugh, ugh, ugh. Egg on my face. That's a huge bug I introduced in the 5.4 release when I was rushing things in. Should be Sequence. Can we rush a 5.5.1 in for that?

**Comment by mysticmind** [comment]
> @mysticmind Ugh, ugh, ugh. Egg on my face. That's a huge bug I introduced in the 5.4 release when I was rushing things in. Should be Sequence. Can we rush a 5.5.1 in for that?

Sure Jeremy, will push out a 5.5.1 with the fix.

**Pull request merged**
