### PR TITLE
Live aggregate linq selector

### PR DESCRIPTION
**Pull request by jedidja**

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@jedidja The code looks good, but can you rebase this on master first?

**Comment by jedidja** [comment]
@jeremydmiller Actually do you want me to squash the commits too?

**Comment by jeremydmiller** [comment]
@jedidja If you don't mind, yes. Then that'll be the very last thing before I pull this in. Thank you again for taking this on and helping clear out the backlog.

**Comment by mysticmind** [comment]
@jedidja squash is not required, it can done when we merge the PR by choosing GH "Squash and merge" option.

**Pull request merged**
