### PR TITLE
Explain how to update the docs including code snippets

### PR DESCRIPTION
**Pull request by AlexZeitler**

### CODE REVIEW

**Comment by mysticmind** [comment]
@AlexZeitler with regards to the following:

> Then you can refer to the code example in the Markdown file by using the following syntax:
>
>```markdown
>
>
>```

you could add a the same in code in some unit test file and use it.

**Comment by AlexZeitler** [comment]
@mysticmind makes sense - will do!

**Comment by AlexZeitler** [comment]
@mysticmind doing it and running `mdsnippets` or `docs-build` will include compile the snippet into `CONTRIBUTING.md`.

image

Too bad MarkdownSnippets doesn't have an option to ignore single Markdown files.

**Comment by mysticmind** [comment]
A screenshot is good enough and trivial to do!

**Comment by AlexZeitler** [comment]
@mysticmind Added the screenshot

**Pull request merged**
