### PR TITLE
Added no-op id generation support for non public id members.

### PR DESCRIPTION
**Pull request by JeffN825**

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@JeffN825 Cool, hadn't really thought of this case. Can you add some tests thought? Build a DocumentMapping w/ that type and see what Id generation strategy is assigned maybe?

**Comment by jnevins-gcm** [comment]
I must admit, I'm super confused by the layout of your tests. I can't seem to figure out what the naming convention is, or what tests belong where. I guess I'd add this to Testing.Generation? And the model class to the Examples namespace?

**Comment by jeremydmiller** [comment]
I'd put this in the `Marten.Testing.Schema` namespace, and just put the sample doc class in the same file as your test file. Just something descriptive like `uses_no_id_generation_for_non_public_id_Tests` for the name.

**Comment by JeffN825** [comment]
Added a test.

**Pull request merged**
