### PR TITLE
Asynchronous path for document cleaning

### PR DESCRIPTION
**Pull request by danielmarbach**
For symmetry reasons introduced the async methods on the document cleaner API as well.

### CODE REVIEW

**Comment by danielmarbach** [comment]
@jeremydmiller This is done from my point of view

**Comment by jeremydmiller** [comment]
@danielmarbach I should have shut this one down earlier. I think this is just unnecessary complexity and clutter in the codebase. I'd rather we didn't take this in. Document cleaner is strictly for testing.

**Comment by danielmarbach** [comment]
Well then the API belongs into a different package. But even then, for example in our acceptance testing solutions we are purely async. The complexity argument: Well that is driven by the design decision to support sync and async overloads. So you either say: production lib is sync and async and then all APIs follow that guideline, which means the cleaner has to follow that rule as well OR you move it into separate package and come up with the rule where you say: testing code will not be async but sync only because of reasons.

**Comment by CoreyKaylor** [comment]
Now that the API churn has settled down a bit, rebase off the latest master if you're still interested in getting this in. Sorry if this causes some inconvenience.

**Pull request closed without merging**
