### PR TITLE
Fixes of event type sorting for pattern matching, encapsulating logic in `EventTypePatternMatchFrame`

### PR DESCRIPTION
**Pull request by svrx**
After upgrade to version 6 some issue have been identified with compilation of generated code.
When a projection depends on events from different levels of the same inheritance chain, the sorting of methods performed during code generation has been found to be non-deterministic.

See more in #2749.

Current PR provides fixes and tests for such scenario.

### CODE REVIEW

**Comment by svrx** [comment]
After discussion with @jeremydmiller, still pending providing an integration test for the scenario,  but submitting here for review of implementation and potential consideration for the upcoming 6.3.0 release.

**Comment by svrx** [comment]
Integration test covering this scenario has been added, please let me know if it meets the expectations.

**Comment by svrx** [comment]
Thanks for merging this one. When can I expect a release with it included?

**Comment by oskardudycz** [comment]
@svrx, I think that it should be available in 6.4.1

**Pull request merged**
