### PR TITLE
Document additional plv8 options for newer versions of PostgreSQL.

### PR DESCRIPTION
**Pull request by apereiratl**

### CODE REVIEW

**Comment by mysticmind** [comment]
@apereiratl You have sent the changes to docs in the prior PR #1422 which I have already reviewed. I think you can close this PR.

**Comment by apereiratl** [comment]
I will fix the other commit. I'd much rather have them separate to allow easy tracking of changes.

**Comment by oskardudycz** [comment]
Congratulations @apereiratl! You just become Marten contributor! 🕺

**Comment by apereiratl** [comment]
> 
> 
> Congratulations @apereiratl! You just become Marten contributor! 🕺

Thank you @oskardudycz. Happy to be here. Hope to have a long, productive stay.

**Pull request merged**
