### PR TITLE
Reference assemblies of document's base types recursively in code generation 

### LINKED ISSUE #100: 'Compilation failures' when storing object which inherits class with "Id" property from another assembly
'Compilation failures' when storing object which inherits class with "Id" property from another assembly

Marten complains when the "Id" property for a stored object resides in an inherited class which resides in different assembly. 

**Look at bellow examples:**

Project structure:

    MartenPrimer/ (console app, references MartenPrimer.Core)
        Program.cs
        User.cs
    MartenPrimer.Core/ (class library)
        AbstractEntity.cs

Program.cs

    using (var session = store.OpenSession())
    {
        var user = new User();
        user.FullName = "The Marten";
        session.Store(user);    // EXCEPTION HAPPENS HERE
        session.SaveChanges();
    }

User.cs

    public class User: AbstractEntity
    {
        public string FullName { get; set; }
    }

AbstractEntity.cs

    public abstract class AbstractEntity
    {
        public AbstractEntity()
        {
            Id = Guid.NewGuid();
            DateCreated = DateTime.UtcNow;
        }

        public Guid Id { get; set; }
        public DateTime DateCreated { get; }
    }

**UseCase1 (compilation failures when Store<T>(entity) is called at runtime)**

Exact code structure like above, it throws invalid operation exception with compilation message errors.

**UseCase2 (works)**

If I remove "Id" property from AbstractEntity, and put it inside User class, works fine. It does not complain about "DateCreated" or other properties.

**UseCase3 (works)**

If I move AbstractEntity class in the same assembly as User class, works fine.

**Full exception message:**

    Compilation failures!

    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)
    CS0012: The type 'AbstractEntity' is defined in an assembly that is not referenced. You must add a reference to assembly 'MartenPrimer.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
    CS1061: 'User' does not contain a definition for 'Id' and no extension method 'Id' accepting a first argument of type 'User' could be found (are you missing a using directive or an assembly reference?)

    Code:

    using Marten;
    using Marten.Linq;
    using Marten.Schema;
    using Marten.Services;
    using Marten.Util;
    using MartenPrimer;
    using Npgsql;
    using NpgsqlTypes;
    using Remotion.Linq;
    using System;
    using System.Collections.Generic;

    namespace Marten.GeneratedCode
    {

        public class UserStorage : IDocumentStorage, IBulkLoader<User>, IdAssignment<User>
        {

            public UserStorage()
            {

            }

            public Type DocumentType => typeof (User);

            public NpgsqlCommand UpsertCommand(object document, string json)
            {
                return UpsertCommand((User)document, json);
            }

            public NpgsqlCommand LoaderCommand(object id)
            {
                return new NpgsqlCommand("select data from mt_doc_user where id = :id").With("id", id);
            }

            public NpgsqlCommand DeleteCommandForId(object id)
            {
                return new NpgsqlCommand("delete from mt_doc_user where id = :id").With("id", id);
            }

            public NpgsqlCommand DeleteCommandForEntity(object entity)
            {
                return DeleteCommandForId(((User)entity).Id);
            }

            public NpgsqlCommand LoadByArrayCommand<T>(T[] ids)
            {
                return new NpgsqlCommand("select data, id from mt_doc_user where id = ANY(:ids)").With("ids", ids);
            }

            public NpgsqlCommand UpsertCommand(User document, string json)
            {
                return new NpgsqlCommand("mt_upsert_user")
                    .AsSproc()
                    .With("id", document.Id)
                    .WithJsonParameter("doc", json);
            }

            public object Assign(User document)
            {
                if (document.Id == System.Guid.Empty) document.Id = System.Guid.NewGuid();
                return document.Id;
            }

            public object Retrieve(User document)
            {
                return document.Id;
            }

            public NpgsqlDbType IdType => NpgsqlDbType.Uuid;

            public object Identity(object document)
            {
                return ((MartenPrimer.User)document).Id;
            }

            public void RegisterUpdate(UpdateBatch batch, object entity)
            {
                var document = (MartenPrimer.User)entity;
                batch.Sproc("mt_upsert_user").Param(document.Id, NpgsqlDbType.Uuid).JsonEntity(document);
            }

            public void RegisterUpdate(UpdateBatch batch, object entity, string json)
            {
                var document = (MartenPrimer.User)entity;
                batch.Sproc("mt_upsert_user").Param(document.Id, NpgsqlDbType.Uuid).JsonBody(json);
            }

            public void Load(ISerializer serializer, NpgsqlConnection conn, IEnumerable<User> documents)
            {
                using (var writer = conn.BeginBinaryImport("COPY mt_doc_user(id, data) FROM STDIN BINARY"))
                {
                    foreach (var x in documents)
                    {
                        writer.StartRow();
                        writer.Write(x.Id, NpgsqlDbType.Uuid);
                        writer.Write(serializer.ToJson(x), NpgsqlDbType.Jsonb);

                    }

                }

            }

        }

    }

### PR DESCRIPTION
**Pull request by bojanv91**
Closes #100

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@bojanv91 The tests look good, but I think we should do the references instead by using the [Assembly.GetReferencedAssemblies()](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.getreferencedassemblies(v=vs.110).aspx) to recursively add assembly references. I'd rather that we search for and register the dependency assemblies by making the call to `AssemblyGenerator.ReferenceAssembly()` smart enough to recursively add dependencies without duplicates.

What do you think? I'm concerned about the need to be recursive and missing dependencies of the body of a document class that wouldn't necessarily be obvious from just the base class of the document type.

**Comment by bojanv91** [comment]
>  I'm concerned about the need to be recursive and missing dependencies of the body of a document class that wouldn't necessarily be obvious from just the base class of the document type

@jeremydmiller  Yes, I agree that we should reference all dependent (non duplicate) assemblies of the document type's assembly. But I'm not sure why do we need to recurs over them? Can't think of a scenario... Do you have any scenario where not doing recursive referencing would cause failure?

**Comment by jeremydmiller** [comment]
@bojanv91 I'd be lying if I said "yes", but paranoia says we'd want to do this recursively. I don't know that we have an easy way to know exactly what is and is not really required, so why not just do the big bang thing w/ recursive references to avoid possible compilation failures later?

**Comment by bojanv91** [comment]
Okay, thanks for clarification. Sending commit with this change today.

**Comment by jeremydmiller** [comment]
Bueno, thank you.

**Comment by bojanv91** [comment]
@jeremydmiller Is it okay like this?

**Comment by jeremydmiller** [comment]
@bojanv91 Looks good to me, I'm pulling it in. The mechanics will change ever so slightly when we do the CoreCLR support, but let's worry about that when we get there.

**Pull request merged**
