### PR TITLE
Add ignore case constructor overload for StringContains

### PR DESCRIPTION
**Pull request by mysticmind**

### CODE REVIEW

**Comment by mysticmind** [comment]
Please use this PR instead of #873

**Comment by mysticmind** [comment]
@nehapuniani is using a sample query as below:
```
var searchTags = new List<string> { "Test1", "TEST2" };
var results = session.Query<Contact>().Where(x => x.Tags.Any(q => q.Name.Contains(searchTags[0], StringComparison.OrdinalIgnoreCase)));
```

When I try out the above, it actully results in `NotSupportedException` since for a collection, only `==` is supported within `Any()`. Hence the original fix provided by @nehapuniani won't work (this PR was raised on her behalf by me).

The solution is to fall to plain sql query as below:
```
session.Query<Contact>($"SELECT d.data FROM public.mt_doc_contact d,LATERAL jsonb_array_elements(d.data->'Tags') t WHERE t.value->>'Name' ILIKE '{searchTags[0]}'");
```

@nehapuniani If you have any further comments or thoughts, let me know. Otherwise I will close this PR by tomorrow.

**Comment by nehapuniani** [comment]
ILike is not a good solution as it will drastically affect the performance. 
Does Jeremy or you have a better solution ?
Thanks, Neha

**Comment by mysticmind** [comment]
You could use equals check using the SQL as below:
```
session.Query<Contact>($"SELECT d.data FROM public.mt_doc_contact d,LATERAL jsonb_array_elements(d.data->'Tags') t WHERE t.value->>'Name' = '{searchTags[0].ToLower()}'");
```

**Comment by nehapuniani** [comment]
That's exactly what i am doing and this adds case sensitivity and that was the issue that i reported. Jeremy said overloading that method will solve the issue. We need better solution.
Thanks, Neha

**Comment by mysticmind** [comment]
I am closing this PR since the applied changes don't solve the underlying problem at hand. Few proposals provided, not sure what else we could do here.

@nehapuniani you could raise a new issue and outline the details. A similar issue #834 is already there, you could add your comments to the existing issue as well.

**Pull request closed without merging**
