### PR TITLE
Concurrency check for Update in DocumentSessionBase

### PR DESCRIPTION
**Pull request by luboshl**
I've added support of concurrency check when `Update` method of `DocumentSessionBase` is used. It is based on implementation used for `Store` method.

### CODE REVIEW

**Review by oskardudycz — CHANGES_REQUESTED** [review]
@luboshl, thank you for the changes. Could you add a test that’s checking if the versioning work for Update after this change?

**Comment by luboshl** [comment]
> @luboshl, thank you for the changes. Could you add a test that’s checking if the versioning work for Update after this change?

@oskardudycz, I've added the tests. Two of them (`update_with_stale_version_throws_exception` and `update_with_stale_version_throws_exception_async`) are failing when you run them before the the commit with changes for Update method. After this commit all four of them succeeds.

What I don't understand is this condition that I copied from Store method:

```csharp
if (Concurrency == ConcurrencyChecks.Disabled && storage.UseOptimisticConcurrency)
````

I would expect something like
```csharp
if (Concurrency == ConcurrencyChecks.Disabled || storage.UseOptimisticConcurrency == false)
```

What am I missing?

**Review by oskardudycz — APPROVED** [review]
Looks good to me 👍

**Comment by oskardudycz** [comment]
> What I don't understand is this condition that I copied from Store method:
> 
> ```cs
> if (Concurrency == ConcurrencyChecks.Disabled && storage.UseOptimisticConcurrency)
> ```
> 
> I would expect something like
> 
> ```cs
> if (Concurrency == ConcurrencyChecks.Disabled || storage.UseOptimisticConcurrency == false)
> ```
> 
> What am I missing?

Indeed it looks suspicious. It looks like it is either for the non-default scenarios when the optimistic concurrency setting is enabled on the document level or some mishap. @jeremydmiller, do you remember what the reason is? It looks lik

**Comment by jeremydmiller** [comment]
@oskardudycz That was to be able to manually override the concurrency checks on a document type with concurrency protection. In that case, you had to switch to using a different document operation type altogether. That code is actually correct.

**Comment by jeremydmiller** [comment]
I added an extra test for the "concurrency checks disabled", but it was all good, so this is in.

**Pull request merged**
