### PR TITLE
fix: Make MultiStreamProjection usable for AggregateTo<>

### LINKED ISSUE #2889: MultiStreamProjection is not supported with QueryAllRawEvents().AggregateTo<>()
As the title says, MultiStreamProjections are not supported, only SingleStreamProjection.

### PR DESCRIPTION
**Pull request by Blackclaws**
Adds support for MultiStreamProjection to AggregateTo<>

Open issue still to solve is that the Id of the resulting document is not set.

Closes #2889

### CODE REVIEW

**Comment by Blackclaws** [comment]
So see also my comments on discord. But essentially, the way QueryAllRawEvents.ToAggregate works is not really conducive to MultiDocument outputs as well as setting any sort of Id on the result. The reason being that there is no grouping performed on the events and there is only a single expected output, while a MultiStreamProjection might have two or more outputs (if using Identities) and also QueryAllRawEvents.ToAggregate does try to use all events that are in the collection.

**Comment by jeremydmiller** [comment]
I think this is fine for what it is. It's not a usage that I'd ever be recommending, it's more of just a "if there's nothing else you can do, try this".

I don' think the grouping should have any effect on AggregateTo() in the first place.

**Comment by Blackclaws** [comment]
> I think this is fine for what it is. It's not a usage that I'd ever be recommending, it's more of just a "if there's nothing else you can do, try this".
> 
> I don' think the grouping should have any effect on AggregateTo() in the first place.

You're probably right as its also consistent with how AggregateTo works for SingleStreamAggregations. I'll remove the WIP.

**Comment by jeremydmiller** [comment]
This got addressed a little differently

**Pull request closed without merging**
