### PR TITLE
Add index on column doc_type, see #765

### PR DESCRIPTION
**Pull request by mdissel**

### CODE REVIEW

**Comment by jeremydmiller** [comment]
Hey, could you throw a unit test on `DocumentTable` for "not hierarchical, no index" and "hierarchical, so index"? Otherwise that looks good to me

**Comment by mdissel** [comment]
But if there's no hiearchy the column docType is not created..

**Comment by jeremydmiller** [comment]
@mdissel I just meant the negative case is all. I'm good with this and pulling it now.

Thanks for taking this on.

**Comment by jeremydmiller** [comment]
@mdissel Couple issues with this one that I'm taking care of:

* There was already a separate facility to index the Deleted column, so I just removed the code in DeletedColumn
* The unit test wasn't written correctly and failed. Easy fix though.

**Comment by mdissel** [comment]
Thanks.. i will run all the tests next time.. sorry!

**Pull request merged**
