### PR TITLE
GH 962 - fix, bug test, updated docs

### PR DESCRIPTION
**Pull request by KahuKirikiri**
This PR includes...
1. Fix for GH-962 using calculated properites
2. A test for the bug with document sample mark up
3. Added documentation on how to use IInitialData
4. Upgrade of xunit and xunit.runner.visualstudio to latest version

### CODE REVIEW

**Comment by KahuKirikiri** [comment]
There is definitely something broken with those `can_generate_database_objects_when_tenanted` tests. You could probably re-run the AppVeyor build several times and get non-deterministic passes/failures because that's what I'm seeing running the tests locally, including on the master branch.

**Comment by jeremydmiller** [comment]
@KahuKirikiri I'll pull it down locally tomorrow and see what's up. I don't have any particular ideas about it yet though.

**Comment by jeremydmiller** [comment]
@KahuKirikiri I'm looking at this locally now

**Comment by jeremydmiller** [comment]
Got it in w/ the rebase. Can't reproduce the DDL problems, but we'll watch for it on AppVeyor. Confident it's not related to this at all.

**Pull request closed without merging**
