### PR TITLE
Fix async daemon null operation deadlock

### PR DESCRIPTION
**Pull request by Hawxy**

### CODE REVIEW

**Comment by mysticmind** [comment]
@Hawxy does this also fix https://github.com/JasperFx/marten/pull/1974?

**Comment by Hawxy** [comment]
@mysticmind yes it does appear to

**Review by mysticmind — APPROVED** [review]
Looks good to me 👍

**Review by oskardudycz — APPROVED** [review]
Thanks, @Hawxy 👍

**Pull request merged**
