### PR TITLE
Extract base identity map

### PR DESCRIPTION
**Pull request by tim-cools**
DirtyTrackingIdentityMap and IdentityMap now share most of their logic in a base class.

This probably fixed a bug with duplicated id's in DirtyTrackingIdentityMap by using object instead of int (id.GetHashcode())
See: https://github.com/JasperFx/marten/issues/179

+ Plus use a default list of listeners instead of a null value (see previous PR)

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@tim-cools Hey Tim, can you make sure that's rebased on master? We did switch the identity map to using `object` because of some problems that @jenspettersson ran into.

**Comment by tim-cools** [comment]
@jeremydmiller true, but that was only fixed in IdentityMap but not in DirtyTrackingIdentityMap (https://github.com/JasperFx/marten/pull/181)

**Comment by jeremydmiller** [comment]
Ugh, okay. Thanks for doing this, I'll get it in my tomorrow morning.

**Comment by jenspettersson** [comment]
Damn, my bad. I only ran into #181 in the IdentityMap, never tried the DirtyTrackingIdentityMap and missed it completely. Sry guys

**Comment by jenspettersson** [comment]
@jeremydmiller @tim-cools want me to fix the `DirtyTrackingIdentityMap` in master or shall we just wait until this gets pulled in?

**Comment by tim-cools** [comment]
No worries, I only ran into this because I noticed that they both used a different key type. That is the nice thing about looking at the code with many different people. 
And it should be fixed with this pull-request, so I would not bother fixing it on master. They now share a base class with the main logic so we only have to maintain it in one place.

**Comment by jeremydmiller** [comment]
Got it!

**Pull request closed without merging**
