### PR TITLE
Added failing tests for #870 - linq support for child collection and child collection of child collection

### PR DESCRIPTION
**Pull request by oskardudycz**
Failing tests for scenarios from #870

### CODE REVIEW

**Comment by mysticmind** [comment]
@oskardudycz Looks like the recent fixes on #1334 have resolved this issue. Can you please fix the file conflict and run a test on this?

**Comment by oskardudycz** [comment]
@mysticmind I rebased the master, unfortunately, it seems that those queries are still not supported.

**Comment by mysticmind** [comment]
@jeremydmiller @oskardudycz @jokokko I was looking at ToroDB to learn more since it also works on top of Postgres JSONB, really like the model they adopted to not store document with nested structures but break it down into sub documents and store it separately. See the details from the ToroDB internals as below:
> JSON documents are split by hierarchy levels into “subdocuments”, which contain no nested structures. Each subdocument level is stored separately
Subdocuments are classified by “type”. Each “type” maps to a different table.

It will be interesting to read this [doc](https://info.citusdata.com/rs/235-CNE-301/images/ToroDB_internals_How_to_Create_NoSQL_on_top_of_SQL_-_Alvaro_Hernandez.pdf)

Possibly if we build upon this idea, I think we can easily deal with querying nested child collection across multiple Postgres versions without using JSONPath(SQL/JSON) which is available only from PG12+.

Please let me know your thoughts.

**Comment by jeremydmiller** [comment]
I'm grabbing this into a local branch today. I'm planning to finally beat this with some CTE magic

**Comment by jeremydmiller** [comment]
Got this in locally now.

**Pull request closed without merging**
