### PR TITLE
[WIP] Introduction of MemoryPool based CharTextWriter

### PR DESCRIPTION
**Pull request by Scooletz**
An experimental PR that changes `CharArrayTextWriter` pooling behavior from the custom one to one based on `MemoryPool<char>` from `System.Memory` package

### CODE REVIEW

**Comment by Scooletz** [comment]
I tried to follow this comment from travis https://github.com/travis-ci/travis-ci/issues/8990#issuecomment-385357592 to make the build green. I don't know travis much and if somebody could help me in enabling C# 7.2 for this PR I'd be grateful.

**Comment by mysticmind** [comment]
@jeremydmiller could you please rerun the travis ci test for this PR?

**Comment by Scooletz** [comment]
Hey @jeremydmiller , did you get a green build of it? I can't see the status and this was marked as WIP 😅

**Comment by jeremydmiller** [comment]
Yep.

**Pull request merged**
