### PR TITLE
add IAsyncDisposable support

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by mysticmind** [comment]
@SimonCropp There looks to be few blinking tests, I had to re-run the failing CI jobs on this PR and your other PR.

**Comment by SimonCropp** [comment]
@mysticmind thanks. i was wondering about those.

**Review by mysticmind — APPROVED** [review]
Thanks @SimonCropp, looks good to me 👍

**Review by oskardudycz — APPROVED** [review]
@SimonCropp thank you for PR. Looks good 👍

**Pull request merged**
