### PR TITLE
Use async versions of dispose and close methods

### PR DESCRIPTION
**Pull request by YohDeadfall**
Npgsql starting version 4.1 supports async versions of `Close` and `Dispose` methods.

### CODE REVIEW

**Comment by YohDeadfall** [comment]
Marten is targeting .NET Framework and .NET Standard 2.0, so it isn't able to consume this API and Npgsql unfortunately doesn't provide this methods while for others it does.

@roji Looks like we have missed something.

**Comment by YohDeadfall** [comment]
@jeremydmiller @oskardudycz would you like to have access to async methods in the next patch release if @roji agrees with it?

**Comment by roji** [comment]
@YohDeadfall not exposing async versions for .NET Standard 2.0/.NET Framework was semi-intentional. If people actually request this I guess we could expose them in a patch - nobody's ever asked :)

**Comment by oskardudycz** [comment]
@YohDeadfall thank you for giving the heads up. Currently, we're not supporting (yet) `IAsyncDisposable` anywhere in our codebase. Technically from SemVer perspective adding new feature should be minor, but if it's not breaking anything then I'm fine with exposing that via a patch release.

**Pull request merged**
