### PR TITLE
Projections generated code may fail compilation due to order of switch case statements

### PR DESCRIPTION
**Pull request by svrx**
After upgrade to version 6 some issue have been identified with compilation of generated code. 
When a projection depends on events from different levels of the same inheritance chain, the sorting of methods performed during code generation has been found to be non-deterministic.

Example:
```csharp
//Events
class BaseEvent {}
class DerivedEventA: BaseEvent {}
class DerivedEventB: BaseEvent {}

//Projection
class Aggregate{
   void Apply(DerivedEventA @event):
   void Apply(DerivedEventB @event):
   void Apply(BaseEvent @event):
}
```

Will sometimes throw a `Unreachable code detected` error during compilation of generated code, due to having `BaseEvent` appearing in switch case order before any of the derived events.

Further investigation has shown that root cause of the issue may reside in  `EventTypeComparer` implementation.  
At first glance it looks fine, although the resolution of comparison isn't granular enough, hence when being processed for sorting through .Net internals (depending on API flavour used, may be a QuickSort or Heap+Introspective sort), and optimizations are applied in regards divide and conquer nature of algorithms, having assumptions taken based on partitions and equality (as per result of comparer), which in turn results in some entries never being compared, since all the items in the partition being processed having been reported to be equal by the comparer (comparer returns 0).

Relates to #2749.

### CODE REVIEW

**Comment by svrx** [comment]
Relates to #2749.

**Comment by svrx** [comment]
The implementation was updated from prior version for simplicity and better encapsulation.
The sort method was encapsulated in `EventTypePatternMatchFrame` has that's where the logic is relevant and changed back to using simpler comparer originally used in combination with a different sort approach to avoids original issues.
All usages were updated accordingly.

**Comment by jeremydmiller** [comment]
I'm working on this one now

**Comment by jeremydmiller** [comment]
@svrx Just for your later reference, the usage of `SortedList` had some unexpected side effects where it would lose several event handlers. I switched the code to just use `List<T>.Sort()`, and that did the trick.

**Comment by svrx** [comment]
@jeremydmiller you're right, apologies for overlooking that fact. In this case this PR is doing nothing. `EventTypePatternMatchFrameOrderTests` are failing the same way they would have before. Are these test run as part of your validation pipelines?
I can revert comparer to my interim implementation that didn't had that issue.
Question before I move with that, are interfaces that events may implement allowed to be used in projections? Or any plans to support something like that?

**Pull request merged**
