### PR TITLE
Update computed_indexes.cs sample

### PR DESCRIPTION
**Pull request by nikodemrafalski**
Enriched index configuration sample to document possible index scopes (Global|PerTenant).

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1538) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1538) before we can accept your contribution.<br/><br/>:x: nikodemrafalski [sign now](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1538)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/JasperFx/marten?pullRequest=1538) it.</sub>

**Comment by mysticmind** [comment]
@nikodemrafalski can you please re-base this PR against branch [3.12](https://github.com/JasperFx/marten/tree/3.12)

**Comment by nikodemrafalski** [comment]
Sure , done

**Comment by mysticmind** [comment]
Thanks @nikodemrafalski

**Pull request merged**
