### PR TITLE
add mt_created_timestamp field to documents

### PR DESCRIPTION
**Pull request by ribbal**
Adds a mt_created_timestamp field and resolves: https://github.com/JasperFx/marten/issues/2740

### CODE REVIEW

**Review by oskardudycz — CHANGES_REQUESTED** [review]
@ribbal, that looks like a good starting point. Could you check and fix the failing tests and and new for the added column?

You can start by finding all references for `SchemaConstants.LastModifiedColumn` in tests and updating them accordingly.

**Comment by ribbal** [comment]
@oskardudycz, I've added/fixed unit tests (hope I didn't miss anything)

**Comment by jeremydmiller** [comment]
@ribbal Couple notes, but there both big things:

1. I would ask that this new "created" column be **opt in** and not enabled by default. *Some* people would want this, *many* won't, but the way it's coded now would result in everybody having to do database migrations to take this in. Please made the new column **opt in** by setting the `Enabled = false` on the metadata column
2. With the opt in model, you'll need actual integration tests for this column being enabled with some combination of bulk loading, store/insert/update a document.

**Comment by ribbal** [comment]
@jeremydmiller, I've made the new column an **opt-in**, and added some integration tests.

**Review by oskardudycz — APPROVED** [review]
@ribbal, I renamed the initial `CreatedTimestamp` to `CreatedAt` to align it with other field conventions (e.g. `DeletedAt`). I also fixed a few tests.

I'm pulling it in.

@ribbal, thanks for the contribution and effort in delivering it 👍

**Comment by ribbal** [comment]
> @ribbal, I renamed the initial `CreatedTimestamp` to `CreatedAt` to align it with other field conventions (e.g. `DeletedAt`). I also fixed a few tests.
> 
> I'm pulling it in.
> 
> @ribbal, thanks for the contribution and effort in delivering it 👍

Yeah, I saw that.  I would have been happy to make that change if you would have let me know the naming convention.

There are a few references to 'created_timestamp' still hanging around in the tests.  Shall I fix them, or leave them to you?

**Comment by oskardudycz** [comment]
@ribbal, no worries; I didn't want to discourage or overtake your work. I just wanted to get it into v6.3.0. Which was just released :)

If you see some leftovers, then that would be much appreciated. Also some docs if you're open to that :)

**Comment by ribbal** [comment]
I've just upgraded to v6.3.0; it's good to see the new mt_created_at field 😄 

I'll clean-up the leftovers.  If you let me know what docs need updating, and it's just a copy from existing last_modified docs, I'll take a look.

**Pull request merged**
