### PR TITLE
Added support for compiled stats

### LINKED ISSUE #353: Support Stats() within compiled queries
Hopefully this is going to be rinse and repeat after @nieve 's work on Include() + compiled queries

### PR DESCRIPTION
**Pull request by nieve**
fixes #353 
Will add documentation tomorrow, but thought I should open the PR if anyone wishes to have a peek at the code to make sure it's all hunky dory.

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@nieve Code looks fine to me. There's another one coming up soon w/ the "soft deletes", and this one will probably be a nice guide on how to do the soft deletes.

**Comment by nieve** [comment]
Docs added, this is good to go :)
Will be more than happy to take on the soft deletes one- feel free to give me a shout when it comes.

**Comment by jeremydmiller** [comment]
@nieve Can you peek at the test that's failing: http://build.fubu-project.org/viewLog.html?buildId=47577&tab=buildResultsDiv&buildTypeId=Marten_Master? Soft deletes are 2nd on my queue, but I don't mind handing it off. If you wanna do that, I'll go put in my notes about the mechanics to the GH issue. Thought it might be nice if you didn't have to do every single Linq customization;)

**Comment by nieve** [comment]
@jeremydmiller don't have access to the CI. Which test is that?

**Comment by jeremydmiller** [comment]
Huh, you should be able to log on as a guest.

It's `end_to_end_query_with_include_Tests.compiled_include_to_list`

**Comment by nieve** [comment]
Oh, this is odd- I've removed the commit that had this test in and pushed -f to my branch. Should I create another PR on another branch?

**Comment by jeremydmiller** [comment]
I say you do whatever's easiest for you on the Git mechanics.

**Pull request closed without merging**
