### PR TITLE
split targets up a little

### PR DESCRIPTION
**Pull request by adamralph**
I find it's usually better to isolate targets to one significant operation, so that you get more specific success/failure messages and timings.

### CODE REVIEW

**Comment by adamralph** [comment]
The CI build seems to fail intermittently for unrelated reasons. I've touched the branch 4 times now to re-trigger the build.

The first and second builds succeeded on Appveyor but failed on Travis CI. The third build succeeded on Travis CI but failed on Appveyor. The fourth build failed on Travis CI and is still running on Appveyor. The fifth build is pending...

I have to go AFK now, but I can trigger the build later if it fails again. In the meantime, feel free to trigger the build if required.

**Comment by mysticmind** [comment]
@adamralph Thanks for the PR, splitting to smaller targets makes sense. My goal when I implemented this was to closely match the existing rake script.

I will have a look at it tomorrow in my morning and merge this PR.

**Comment by mysticmind** [comment]
I will take a look at the build failures, no worries. Since most are integration tests, it is bound to fail sometimes

**Comment by adamralph** [comment]
Woot! The builds are both green. 🎉

**Pull request merged**
