### PR TITLE
Fix `pg_sequences` related failures in PG9.6 tests

### PR DESCRIPTION
**Pull request by mysticmind**
Fix to run drop sequences using `pg_sequences` only for PG ver 10 or above

### CODE REVIEW

**Comment by mysticmind** [comment]
All the existing Docker containers in DockerHub for PG9.6 and plv8 build from source looks to be brokwn due to V8 build changes. I am going to prepare a Docker image for PG9.6 and plv8. Until then I am going to disable PG9.6 build in the Azure Pipelines CI.

**Comment by mysticmind** [comment]
I have setup a fresh docker container for PG9.6 and plv8, the docker container looks to be working fine. 

We have to fix the other unit test errors pertaining to feature toggles for different PG versions.

**Comment by jokokko** [comment]
Think #1278 supplants this (by switching to information_schema.sequences, as opposed to the view).

**Comment by mysticmind** [comment]
@jokokko I am closing and will merge #1278 shortly.

**Pull request closed without merging**
