### PR TITLE
Passing and failing tests for #624

### PR DESCRIPTION
**Pull request by ericgreenmix**

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@ericgreenmix I'm looking at this right now.

**Comment by jeremydmiller** [comment]
Ah, okay, I get it. I think the way I'd want to approach this is to make the daemon on a rebuild to first look for the latest sequence id, then keep the fetching going until then.  It's getting defeated right now because the gap in sequence is bigger than the page, and the daemon is stopping when it hits an empty set.

**Comment by ericgreenmix** [comment]
Ah that makes sense. Sounds like a good solution to me

**Comment by jeremydmiller** [comment]
@ericgreenmix Okay, the next question is "how did you get the event store into this state in the first place?"

**Comment by ericgreenmix** [comment]
Eh, what exactly do you mean by that? We have tons of events going into our event store. When an event is stored and then over 100 different event types get stored, then that same event type gets stored again, that is when we start seeing the issue.

**Comment by jarroda** [comment]
@jeremydmiller looking at the `Fetcher` code, it looks like the issue might be the `fetchNextPage`.  We don't actually have gaps in our event store (there are events for every sequence number), but the query 
```
select seq_id from {_selector.Events.DatabaseSchemaName}.mt_events where seq_id > :last and seq_id <= :limit and age(transaction_timestamp(), {_selector.Events.DatabaseSchemaName}.mt_events.timestamp) >= :buffer order by seq_id;
{_selector.ToSelectClause(null)} where seq_id > :last and seq_id <= :limit and type = ANY(:types) and age(transaction_timestamp(), {_selector.Events.DatabaseSchemaName}.mt_events.timestamp) >= :buffer order by seq_id;
```
seems to be filtering on type and grabbing the seq_id window at the same time.  So if there aren't any events of the particular type in that window, you'll get 0 results.  This I think is what is causing the issue to manifest itself in our system.

**Comment by jeremydmiller** [comment]
@jarroda Yeah, I bumped into that w/ Eric's test. I'll add another test that runs continuously with big gaps somehow. This is turning into a much bigger issue than I was anticipating.

**Pull request merged**
