### PR TITLE
1858 - Async daemon - Shard never reaches most up to date sequence number

### PR DESCRIPTION
**Pull request by julienperignon**
For issue #1858

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1859) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1859) before we can accept your contribution.<br/><br/>:x: julienperignon [sign now](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1859)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/JasperFx/marten?pullRequest=1859) it.</sub>

**Comment by mysticmind** [comment]
@julienperignon unit tests are passing
. The failed one is a different issue though. :-)

**Comment by julienperignon** [comment]
@mysticmind  it doesn't on local. I'm consistently getting it to fail

**Comment by mysticmind** [comment]
> @mysticmind it doesn't on local. I'm consistently getting it to fail

Understood. We will try and see if we have a repro.

**Comment by jeremydmiller** [comment]
@julienperignon I'm pulling this down locally right now

**Comment by jeremydmiller** [comment]
This was brought in with a rebase, so I'm closing now. Thanks @julienperignon for the test repo!

**Pull request closed without merging**
