### PR TITLE
Elementary full text search implementation

### PR DESCRIPTION
**Pull request by jokokko**
Could this serve as a basis for #39?

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@jokokko,

Sorry I've been so slow getting around to this one. I'd be happy to take this one in today. I do think we need to add some additional tests for the database object lifecycle (clean out the DB, see it get reestablished, different schema auto-creation rights).

What else do you think needs to happen to get this production ready?

And docs, but that's no big deal.

**Comment by jokokko** [comment]
@jeremydmiller,

Yeah, the things you mention need to be there... I don't know if the UsingVector is the most elegant way to go, but on the other hand it gives explicit control over naming (maybe omitting that could default to reflecting over the member name and using as part of the name).

I'll hope to find the time to refine this PR soon.

**Comment by jeremydmiller** [comment]
I'm closing because there's no activity here. I think the consensus seems to be to just wait for Postgresql 10.

**Comment by JonCanning** [comment]
Now? I could really use this!

**Pull request closed without merging**
