### PR TITLE
Prevent index re-creation

### PR DESCRIPTION
**Pull request by vadimline**
Fix actual index script column replacement to prevent index re-creation each time

### CODE REVIEW

**Comment by vadimline** [comment]
#702

**Comment by jeremydmiller** [comment]
@vadimline Were you able to run the Marten tests on this one? It failed in CI.

http://build.fubu-project.org/viewLog.html?buildId=48993&tab=buildResultsDiv&buildTypeId=Marten_Master

**Comment by vadimline** [comment]
What a shame, I forgot to check tests. Fix ready.

**Comment by jeremydmiller** [comment]
Got it, the build's green, and I'm pulling this in. Will be in the 1.5 release maybe next week.

**Comment by vadimline** [comment]
Great, thanks.

**Pull request merged**
