### PR TITLE
fix System.IndexOutOfRangeException when selecting JObject from Document

### PR DESCRIPTION
**Pull request by srasch**
fixing #2307 

i added to unit tests to document the issue.

### CODE REVIEW

**Review by mysticmind — APPROVED** [review]
Looks good to me 👍

**Comment by mysticmind** [comment]
@jeremydmiller This PR looks to be a related one to https://github.com/JasperFx/marten/pull/2322

**Comment by jeremydmiller** [comment]
@srasch This one's my fault, I wrote a parallel test and fix before I saw your PR come in. The fix I did was a bit more generic, so I'm gonna keep that one and close this one. I'm sorry about this, but at least the bug is fixed.

**Comment by srasch** [comment]
@jeremydmiller this is fine for me. thank you for the great work :)

**Pull request closed without merging**
