### PR TITLE
Asynchronous versions of everything in the IDocumentSession API

### LINKED ISSUE #16: Asynchronous versions of everything in the IDocumentSession API
More work on this later, but assuming that we're going to the OWIN'ified async all the things, Node.js style event loop kind of world for maximum scalability

### PR DESCRIPTION
**Pull request by ekulakov**
Base async\await support

Closes #16

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@ekulakov Hey, thanks so much for doing this. Everything looked fine from a cursory glance, but it'll be the Monday after New Year's before I can bring this in and push a new nuget.

**Comment by jeremydmiller** [comment]
@ekulakov I'm looking through this now.

**Comment by ekulakov** [comment]
I can try to add several more methods like `SingleAsync()`, `SingleOrDefaultAsync()`, etc

**Comment by jeremydmiller** [comment]
@ekulakov Do you want to do that as a separate PR, or add to this one? I don't see any reason not to take this in whenever you want. The code looks good to me and I like what you did in the internals.

**Comment by ekulakov** [comment]
@jeremydmiller if you don't mind let it be a separate PR

**Comment by jeremydmiller** [comment]
@ekulakov Cool, I'm pulling this in right now then. Thanks!

**Pull request merged**
