### PR TITLE
Refactor and simplify the PagedList implementation

### PR DESCRIPTION
**Pull request by mysticmind**
- Refactor and simplify the PagedList implementation to use
QueryStatistics to use single db query GH-930
- BREAKING CHANGE: AsPagedList and AsPagedListAsync IQueryable<T> is
changed to IMartenQueryable<T>
- BREAKING CHANGE: some of the properties in IPagedList<T> has change been
changed from int to long
- Update unit tests

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@mysticmind If this is a breaking change, can you apply this to the 3.0 branch?

**Comment by mysticmind** [comment]
I just relooked at the changes which I have marked as "breaking change":
- AsPagedList and AsPagedListAsync extension method signature with first parameter changed from IQueryable to IMartenQueryable. Even though the method signature have changed, it is still compatible and won't break existing users.
- IPagedList interface change with properties changed from int to long also won't break existing end users.

Given the above details, I think to have incorrectly commented as "breaking change". Can we merge into master itself?

**Comment by karelg** [comment]
@mysticmind Unfortunately signature change will break things, if we are filtering and ordering results with LINQ before we are calling _AsPagedList_. I think, we should not change the signature, instead we could just check inside _PageList_, if _IQueryable_ is an instance of _IMartenQueryable_ and use the _QueryStatistics_ from it for more efficient query and just fall back to old implementation, if it is not. What do you think?

**Comment by mysticmind** [comment]
@karelg good idea, will change the implementation accordingly.

**Comment by mysticmind** [comment]
@karelg I had a look at it, doing a fallback will be problematic since the IPagedList also has some signature changes. In theory these are still breaking changes since the signature have changed. I think it is better to be pushed to 3.0 branch as suggested by @jeremydmiller

**Comment by mysticmind** [comment]
Based on my prior comments, closing this. I will send a fresh PR for 3.0 branch

**Pull request closed without merging**
