### PR TITLE
Add feature to disable using default tenant to store multi tenanted docs

### PR DESCRIPTION
**Pull request by mysticmind**
- Add feature to disable using default tenant to store multi tenanted docs
- Add unit tests
- Add docs

Fixes GH-1449

### CODE REVIEW

**Comment by tonykaralis** [comment]
This is exactly what I was looking for. Thanks @mysticmind

**Comment by mysticmind** [comment]
@jeremydmiller @jokokko please review the PR.

**Comment by jeremydmiller** [comment]
I'm pulling this in now, but I'm going to deal with the bulk insert like @jokokko suggested

**Comment by jeremydmiller** [comment]
I actually think it's fine the way it is now. It's just adding a new assertion on starting up a document session

**Pull request merged**
