### PR TITLE
A way to handle #460 using the @> operator. Does not use the SqlLocat…

### PR DESCRIPTION
**Pull request by jokokko**
…or from IField as customizing that in JsonLocatorField would break SelectMany implementations :|

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@jokokko I'd be thrilled if that's all the changes required, but at a minimum it needs quite a bit more testing. We need to check that it isn't spitting out multiple references to the same document, either the primary document or the included document. We also need to test it in combination w/ the QueryStatistics and probably within a compiled query too.

**Comment by jokokko** [comment]
@jeremydmiller Indeed, cannot but agree with every statement. But I wanted to present the idea of going with the @> jsonb operator. E.g. currently the JsonLocatorField makes assumptions that make this impractical, or at the very least require touching a much larger (public) surface area than just my few lines on IncludeJoin. Having these concerns addressed before 2.0 is pushed out could be beneficial.

**Comment by jeremydmiller** [comment]
@jokokko "the JsonLocatorField makes assumptions that make this impractical" -- you'll have to refresh my memory, but what do you mean? JsonLocatorField mostly just remembers the path to an element within the JSON document. 

Totally onboard w/ this being in 2.0.

**Comment by jokokko** [comment]
@jeremydmiller As I understand it, it introduces an unnecessary cast. Say I create a GIN index on the IssueList.Issues. With the CAST from JsonLocatorField I get a Join Filter on IssueList.Issues and sequential scan on IssueList, whereby without the cast I get a bitmap heap scan on IssueList yielding massively lower cost. Still very much anecdotal, I'm by no means a PG expert. But if this is the case, then making the required modifications to JsonLocatorField would require touching existing public contracts, not just internal implementation of IncludeJoin (which I fear is the case and thus suitable target to attack in 2.0).

**Comment by jokokko** [comment]
@jeremydmiller To add to the previous, some logs from my dev box, running PG 9.6 with the defaults, as modest as they are. 2.5k IssueList items, each linking (in the domain model sense of things, not DB foreign keys or somesuch) to 3 Issue Items. GIN index on `doc_issuelist.Data->'Issues'`

```sql
explain analyze verbose
select d.data, d.id, d.mt_version, issues.data, issues.id, issues.mt_version from
  public.mt_doc_issuelist as d INNER JOIN
  public.mt_doc_issue as issues ON d.data -> 'Issues' @> to_jsonb(issues.id)
```
```
Nested Loop  (cost=0.10..64170.25 rows=75000 width=403) (actual time=0.020..68.740 rows=15000 loops=1)
  Output: d.data, d.id, d.mt_version, issues.data, issues.id, issues.mt_version
  ->  Seq Scan on public.mt_doc_issue issues  (cost=0.00..605.00 rows=15000 width=179) (actual time=0.004..1.093 rows=15000 loops=1)
        Output: issues.id, issues.data, issues.mt_last_modified, issues.mt_version, issues.mt_dotnet_type
  ->  Bitmap Heap Scan on public.mt_doc_issuelist d  (cost=0.10..4.19 rows=5 width=224) (actual time=0.003..0.003 rows=1 loops=15000)
        Output: d.id, d.data, d.mt_last_modified, d.mt_version, d.mt_dotnet_type
        Recheck Cond: ((d.data -> 'Issues'::text) @> to_jsonb(issues.id))
        Heap Blocks: exact=15000
        ->  Bitmap Index Scan on idxinissues  (cost=0.00..0.10 rows=5 width=0) (actual time=0.002..0.002 rows=1 loops=15000)
              Index Cond: ((d.data -> 'Issues'::text) @> to_jsonb(issues.id))
Planning time: 0.066 ms
Execution time: 69.004 ms
```

Then with the cast produced from `JsonLocatorField`
```sql
explain analyze
select d.data, d.id, d.mt_version, issues.data, issues.id, issues.mt_version from
  public.mt_doc_issuelist as d INNER JOIN
  public.mt_doc_issue as issues ON CAST(d.data ->> 'Issues' as jsonb) @> to_jsonb(issues.id)
```

```
Nested Loop  (cost=0.00..469177.25 rows=18750 width=403) (actual time=0.020..40645.094 rows=7500 loops=1)
  Join Filter: (((d.data ->> 'Issues'::text))::jsonb @> to_jsonb(issues.id))
  Rows Removed by Join Filter: 18742500
  ->  Seq Scan on mt_doc_issue issues  (cost=0.00..303.00 rows=7500 width=179) (actual time=0.005..4.275 rows=7500 loops=1)
  ->  Materialize  (cost=0.00..130.50 rows=2500 width=224) (actual time=0.000..0.057 rows=2500 loops=7500)
        ->  Seq Scan on mt_doc_issuelist d  (cost=0.00..118.00 rows=2500 width=224) (actual time=0.004..0.326 rows=2500 loops=1)
Planning time: 0.384 ms
Execution time: 40646.347 ms
```

It's entirely possible that I'm missing something obvious, but it would seem that the (redundant) cast originating from `JsonLocatorField` is preventing the query planner from using the previously defined index and we go from index scans to sequential scans, in this scenario producing execution times of ~69 milliseconds and ~40 seconds respectively.

**Comment by jeremydmiller** [comment]
@jokokko I say let's add a completely new, semantically different property to JsonLocatorField for something like `RawJsonLocator` or if it's that specific, `JsonCollectionJoinLocator`. Definitely make it be a completely new concept rather than try to change any of the existing logic.

**Comment by jokokko** [comment]
Some convo about this in Gitter. I think eliminating some of the casting that now propagates to many, many areas from JsonLocatorField could produce great perf gains overall, especially when indices are used. I also gave an example of a case where I immediately see a change in behaviour: `CAST(d.data ->> 'Published' AS BOOLEAN) = TRUE)` vs. `d.data -> 'Published' = to_jsonb(TRUE))` wherewby the first case would produce a match if `Published` was serialized to `"true"`, whereas the latter would not. And to that I'd say that if somebody wanted to serialize their booleans as strings, it is up to them to then also do the matching as strings.

**Comment by jeremydmiller** [comment]
@jokokko Do you know why we closed this one, or did I just make a mistake in Github?

**Comment by jokokko** [comment]
@jeremydmiller Seems like a mistake.

**Comment by jeremydmiller** [comment]
@jokokko I'm sorry, but I pulled this one in today and it's just too problematic. Right now it duplicates documents in the main list from the inner join duplication, and I think it's too far a bridge to brute force change all the selectors handle that, and I'm not enthusiastic about forcing it to always do a Distinct().

I want to go back to my original concept for this feature and just issue multiple commands in a batch to avoid that problem.

As for all the cast optimizations on, can you just raise them on #744.

**Pull request closed without merging**
