### PR TITLE
Test cases for failing to rebuild with the async daemon

### PR DESCRIPTION
**Pull request by Jordan466**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1974) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1974) before we can accept your contribution.<br/><br/>:x: Jordan466 [sign now](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1974)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/JasperFx/marten?pullRequest=1974) it.</sub>

**Comment by mysticmind** [comment]
@Jordan466 Looks to be the quite the same as https://github.com/JasperFx/marten/pull/1970

**Comment by Jordan466** [comment]
> @Jordan466 Looks to be the quite the same as #1970

Similar. @Hawxy is trying to demonstrate that the async daemon hangs when it receives a null
These tests are demonstrating that the daemon hangs when `CreateEvent<T>` uses either an interface or abstract base class.
There are no nulls in this case.

**Comment by mysticmind** [comment]
@Jordan466 Thanks for the details, it adds a lot more clarity. Quick note, async daemon unit tests are not included as part of CI due to random flakiness.

**Comment by mysticmind** [comment]
Failing test in this PR are included in https://github.com/JasperFx/marten/pull/1970. Closing this one.

**Pull request closed without merging**
