### PR TITLE
Use PG object comments to record metadata (IDocumentStore FQN)

### PR DESCRIPTION
**Pull request by jokokko**
Record Marten related metadata in PG object comments - first for tables created (so I can e.g. 
```
SELECT relname, description from pg_description
join pg_class on pg_description.objoid = pg_class.oid
where description like 'origin:Marten.IDocumentStore, Marten, Version=1.0.0.51046%'
```

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@jokokko I'll get this one tomorrow morning

**Comment by jeremydmiller** [comment]
@jokokko Except it does need some tests first. I like the idea though.

**Comment by bradyclifford** [comment]
I have a similar PR that injects the JSON schema into the PH meta data comments.

**Comment by jokokko** [comment]
@jeremydmiller Oops, had the tests in stash and forgot to apply them to my commit.

@bradyclifford That's clever. My idea of using PG comments was to easily query the db for Marten related objects and see from which version they originate.

**Comment by bradyclifford** [comment]
Ya I will probably instead just have the JSON Schema in normal script comments. My database team is requiring that they review the JSON schema that will be persisted in the data column before they will approve the DDL script.

**Comment by jeremydmiller** [comment]
@jokokko @bradyclifford I'm going to hold off on this one just until Brady's changes are ready just in case there's any conflicts

**Comment by bradyclifford** [comment]
@jeremydmiller decided that it probably is better that we don't include the Json schema in the table comments.  Instead, we can inject it in after the DDL script is created via our own project CLI.  Unless, you feel it would still be beneficial to have for the entire Marten community.

**Pull request merged**
