### PR TITLE
Fixes #1177 - Backward compatibility of DateTime DuplicatedField

### LINKED ISSUE #1177: Duplicated DateTime changed type from Marten version 2.5 to 3.4
Has the db type for duplicated datetimes changed from version 2.5 to 3.3? In 2.5 it was created with timestamp with time zone, but 3.3 will like it to be timestamp without time zone.

Updated to 3.3 and 4 out of 5 tables fails on migration. All 4 tables has duplicated datetimes, and when I changed the type in the db to without time zone, migration goes well.

Seems this is the place where it did go wrong: https://github.com/JasperFx/marten/commit/24cbd707b31b8b6c85ccce32a157670aac33ff8f#diff-e8e0cf443036c7fa3e51325b1310fc96R40

### PR DESCRIPTION
**Pull request by oskardudycz**
Provided `UseTimestampWithoutTimeZoneForDateTime` to `StoreOptions` for keeping backward compatibility with version 2.x. Set this field to Obsolete, also for DuplicatedFieldEnumStorage.

### CODE REVIEW

**Comment by jeremydmiller** [comment]
Ugh. The code is fine, but it's worth having some kind of "upgrading from 2.* to 3.*" content in the docs 'cause this stuff keeps coming up

**Comment by oskardudycz** [comment]
@jeremydmiller in fact we have it :) I created it some time ago: http://jasperfx.github.io/marten/migration_guide/ 😄

**Comment by oskardudycz** [comment]
@jeremydmiller @Leh2 I also pushed commit with fix for DuplicatedField enum storage posted on our Gitter. See more in https://github.com/JasperFx/marten/pull/1179/commits/9815baff4c3edb411111f56da66b182322f6dcd2

**Comment by oskardudycz** [comment]
Added also fix for selecting `DateTimeOffset` from query
```
session.Query<MyDoc>.Select(x => x.MyDateTimeOffsetProp).ToList()
```
Issue was with wrong casting. Used method `reader.GetFieldValue<T>(0)` instead direct casting (see [here](https://github.com/JasperFx/marten/pull/1179/commits/ef437d610db759b6e010fd320a0452d188b1076e#diff-1ca16fc9f1e5ed8028e23edfe2fb448dR28)

Added also proper tests. 

See more in https://github.com/JasperFx/marten/pull/1179/commits/ef437d610db759b6e010fd320a0452d188b1076e

**Comment by oskardudycz** [comment]
As @jeremydmiller is fine with the changes - I'm merging them.

**Pull request merged**
