### PR TITLE
Pool in existing code for #1466. Separate DI & Asp.Net Core integration?

### PR DESCRIPTION
**Pull request by jokokko**
Skeletons

### CODE REVIEW

**Comment by jeremydmiller** [comment]
Some thoughts:

* Let's add any extensions to `IServiceCollection` to the main Marten library itself
* Any extension method on `IServiceCollection` should be `AddMarten()` just to conform to .Net Core idioms. 
* I'm on the fence for having a separate library for extensions to `IHostBuilder` or `IWebHostBuilder`. I thought it was a pain in other OSS projects to support both across different .Net Core versions. I can be convinced either way, especially if someone else does the work;) There is prior art in Alba or Oakton to look at in this regard.
* I think I'd register the `IDocumentSession` and `IQuerySession` by default. I'd vote for `LightweightSession()` as the default for the `IDocumentSession`
* I like what @jokokko did for chaining the session creation options
* For the `AddMarten()` overloads, I'd recommend at least `AddMarten(string connectionString)` as a super quick start and a more usable `AddMarten(Action<StoreOptions> configure)`. With maybe a 3rd `AddMarten(StoreOptions options)`. And all three chain a fluent interface with additional options to customize the session creation
* For the session creation customization (the registration of IDocumentSession or IQuerySession), I think we should support some kind of optional builder like so:

```
public interface ISessionBuilder
{
    IDocumentSession BuildSession();
    IQuerySession BuildQuerySession();
}
```

so it could be registered like:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMarten(...).BuildSessionsWith<MySessionBuilder>();
}

public class MySessionBuilder : ISessionBuilder
{
    public MySessionBuilder(IDocumentStore store, IDocumentSessionListener[] listeners)
    {
          // do special stuff. Might be using some other services injected in here
          // for multi-tenancy. Or doing some metadata trackign when we get that.
          // or adding listeners that need to come from a DI container
     }
}
```

I'm suggesting using a builder class here instead of using a Lambda service registration to optimize the DI mechanics instead of doing repetitive service location calls.

* I'd keep the option to open sessions with a custom `SessionOptions` too

* For the hosted service for the Marten async daemon, we've got to also do something for ownership in a cluster. Maybe w/ postgresql advisory locks?


I'm sure we'll think of other things later

**Comment by oskardudycz** [comment]
@jeremydmiller @jokokko do we plan to have it in v3.12? I think that at least an initial method for configuring document store and document session would be nice to have plus documentation as this is a huge pain and most often asked question by our users.

I can work on that if you don't have time.

**Comment by oskardudycz** [comment]
As we discussed on Gitter. I agree with @jeremydmiller suggestions. I'd add that in my opinion for the current version it'd be better to:
- keep the DocumentSession as default. People are probably using that most of the time. We could consider using Lightweight in v4 with doing some explanation to the people
- not add host builders extension currently to do not need to do cross-version support (`IWebHostBuilder` in netcoreapp2.x and `IHostBuilder` in netcoreapp3.x`). As 3.1 is currently LTS then we can drop 2.x support in v4 and add just support for  `IHostBuilder` and not have the maintenance pain.

For sure we need to add also good documentation around that.

**Comment by mysticmind** [comment]
#1501 addresses the requirements around DI registration. Closing this one.

**Pull request closed without merging**
