### PR TITLE
Docs linting/spellcheck in PRs

### LINKED ISSUE #1919: Spellcheck / markdown linting for docs
Hi all,

Love the Marten project, and wanted to see if there was an interest in some additional docs CI.

With the [NUnit docs](https://github.com/nunit/docs) project, we utilize GitHub actions to [run markdownlint for formatting and cSpell for spellcheck with all of our docs](https://github.com/nunit/docs/blob/master/.github/workflows/build-process.yml). 

Dropping this here in case you'd find it useful. I could implement when I have time or someone else could probably make quick work of it by adding additional jobs using the steps we take; then it would just be a matter of any ignore rules, corrections, etc. in the PR.

### PR DESCRIPTION
**Pull request by SeanKilleen**
Resolves #1919 

* [x] Add GitHub Action
* [x] Run markdown lint
* [x] Run spellcheck
* [x] cSpell: Add known words (that we want suggested) to `words`
* [x] cSpell: Add words that we want ignored to `ignore`
* [x] markdown-lint: Understand each markdown rule violation and whether it needs to be ignored
* [x] cSpell: ignore snippet contents, e.g. `<!-- snippet: sample_scenario-aggregate-storeandreadinvoice -->`
* [x] Update ignore rules / files
* [x] Resolve legitimate issues

### CODE REVIEW

**Comment by mysticmind** [comment]
@SeanKilleen I have stepped out a bit, will have a look once I am available at my desk in an hour or so.

**Comment by SeanKilleen** [comment]
@mysticmind  -- no worries, I edited my comment above to indicate it's resolved. Sorry for the false alarm!

**Comment by mysticmind** [comment]
@SeanKilleen I will run through the linting errors over the weekend. Some of the errors around fenced code blocks is something which will require a fix to elsewhere.

**Comment by mysticmind** [comment]
I think we can ignore `MD033` and `MD031`

**Comment by mysticmind** [comment]
I see that `sample_exponential_backoff_strategy` is renamed to  `sample_exponential_back-off_strategy` in `docs/events/projections/async-daemon.md`. But haven’t fixed the name used in the code file hence a CI build is failing. You will need to fix https://github.com/JasperFx/marten/blob/0750f4a411c2d711c850fd6ed134c0cb18b2926d/src/CommandLineRunner/AsyncDaemonBootstrappingSamples.cs#L81 as well

**Comment by SeanKilleen** [comment]
@mysticmind ah I see. Thanks for the heads up!

**Comment by mysticmind** [comment]
> Oh and before I forget, one last ask --
> 
> If you happen to have found this valuable, I'm participating in Hackoberfest this year. It's not why I submitted this PR, but if you'd be so inclined as to add a `hacktoberfest-accepted' label to this pull request, that'd be cool.

@SeanKilleen No worries, we will take care of this. Once we review, approve and merge it, it will automatically get counted towards Hackoberfest. Explicit label isn't required.

**Pull request merged**
