### PR TITLE
Events loss in Fetcher under load

### PR DESCRIPTION
**Pull request by simbadltd**
Fix for [Events loss in Marten.Events.Projections.Async.Fetcher under load #1879 ](https://github.com/JasperFx/marten/issues/1879)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1880) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1880) before we can accept your contribution.<br/><br/>:x: simbadltd [sign now](https://cla.dotnetfoundation.org/JasperFx/marten?pullRequest=1880)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/JasperFx/marten?pullRequest=1880) it.</sub>

**Comment by jeremydmiller** [comment]
@simbadltd Hey, we can take this into the 3.* branch, but be aware that the async daemon was 100% rewritten in the v4 release that's coming this month.

**Comment by Leh2** [comment]
Given how critical an error this is, it would be very nice to get this is a 3.* release 🙏 

Can the table migration be done automatically or should it be opt in?

**Comment by simbadltd** [comment]
> Given how critical an error this is, it would be very nice to get this is a 3.* release 🙏
> 
> Can the table migration be done automatically or should it be opt in?

There is no table migration for existing databases since that it might be not safe especially for production.

**Review by oskardudycz — APPROVED** [review]

**Comment by Leh2** [comment]
> > Given how critical an error this is, it would be very nice to get this is a 3.* release 🙏
> > Can the table migration be done automatically or should it be opt in?
> 
> There is no table migration for existing databases since that it might be not safe especially for production.

@simbadltd @oskardudycz how do we utilize this change? Do we need to add the new column `tx_id` manually with default value `0`  and then everything is good to go?

**Comment by oskardudycz** [comment]
@Leh2 if I'm not wrong, looking at the code, then that should be enough. If you'd like to, I can also make this feature opt-in.

**Comment by simbadltd** [comment]
@Leh2 Yes, add the 'tx_id' column typed as `bigint` with default value `0` and not-null constraint. Also, you need to patch `mt_append_event` function as follows:

Append newly added `tx_id` column into the `INSERT` statement and also add the `txid_current()` function to the `INSERT` statement values part:
```
		insert into {databaseSchema}.mt_events
			(seq_id, id, stream_id, version, data, type, tx_id)
		values
			(seq, event_id, stream, event_version, body, event_type, txid_current());
```

**Comment by Leh2** [comment]
Thanks for the answers 🙏 

@oskardudycz giving this is a breaking change, shouldn't this be a major change or added as opt-in?

**Comment by oskardudycz** [comment]
@Leh2, fair, I'll work this week to make it opt-in in the `3.15.6`.

**Comment by Leh2** [comment]
> @Leh2, fair, I'll work this week to make it opt-in in the `3.15.6`.

Hi @oskardudycz. Did you get the time to look at this :)

**Comment by culaja** [comment]
@oskardudycz Is this fix available in Marten 4.0.4 ?
I can't see tx_id column in mt_events table.

**Comment by oskardudycz** [comment]
@culaja nope, it's not. As I mentioned, this fix won't be forward ported. The whole Async Daemon was rewritten from scratch. It's much more reliable than it was before. @jeremydmiller would need to wage if that's something that we need to have in v4.

**Comment by culaja** [comment]
Since I have a case where I manually read events from the mt_events I'm not sure how to be sure that I'll not skip some event in high-load scenarios.

**Comment by oskardudycz** [comment]
You may try serialisable or repeatable read serialisation level for that case. Then it won't be possible to skip any events or have phantoms (https://www.postgresql.org/docs/9.5/transaction-iso.html).

**Comment by jeremydmiller** [comment]
@culaja That's the whole point of the async daemon. What are you doing where you can't use that?

**Comment by culaja** [comment]
I can't find API in Marten like there is in EventStoreDb: to subscribe to all streams by starting from a specific position (sequence).
`Subscibe(Type[] typeOfEventsToSusbcribeTo, long startSequence, Func<EventHandler, Task> eventHandler)`

So this is the reason why I'm reading events directly from mt_events.

**Pull request merged**
