### PR TITLE
Added convenience method DocumentSession for getting last committed e…

### LINKED ISSUE #324: Need a convenience method for finding committed events in the AfterCommit hook
Just to make things more discoverable

### PR DESCRIPTION
**Pull request by jarroda**
…vents.

This potentially fixes #324 

Thoughts?

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@jarroda I think I'd rather see it sitting on the `IChangeSet` interface. I only say that because `IDocumentSession` is already pretty crowded. Plus that way you could access all the events from previous commits if there were any.

**Comment by jarroda** [comment]
Great point.  How about this?

**Comment by jeremydmiller** [comment]
@jarroda That looks like a winner to me. Wanna add a test for it, and then I'll pull it in?

**Comment by jarroda** [comment]
Sounds good.  I'll try to knock that out today.

**Comment by jvdvleuten** [comment]
Nice! I needed this one as well :)

**Comment by jeremydmiller** [comment]
Looks good, I'm pulling this in now.

**Comment by jeremydmiller** [comment]
Pulled in with a rebase.

**Pull request closed without merging**
