### PR TITLE
Add failing test for 577 AsyncDaemon: Rebuild after projections not w…

### PR DESCRIPTION
**Pull request by tim-cools**
…orking

Failing test for #577

### CODE REVIEW

**Comment by jeremydmiller** [comment]
@tim-cools I'll try to look at this tomorrow. Today flew by too fast for me.

**Comment by jeremydmiller** [comment]
@tim-cools Thought I had this fixed, then I think I've hit a different issue with it.

My first question is "why would you do that?"

**Comment by tim-cools** [comment]
@jeremydmiller good question. Currently I host the Daemon my web app, not sure if that is a good idea. And Daemon sounded like it is something expensive to create, so I keep only one instance. So I thought to reuse the single instance to both run the projections and to rebuild the projections. So I stop the Daemon before the rebuild and start it again afterwards. I suspected it might be a problem that two running Daemons start to interact with each-other.

I also had a case where the projections didn't start again after rebuilding. But I couldn't create a tests to reproduce it at first attempt. If it occurs again, I will try to reproduce it in a test again.

**Comment by jeremydmiller** [comment]
@tim-cools Actually, that makes perfect sense to me. I think what we need though is a totally different method for semantics of "restarting" a projection:

1. Delete all existing projected docs
1. Rollback the event encountered counter to 0
1. Process all existing events and continue to run the projection after it catches up

See https://github.com/JasperFx/marten/issues/596 for the new issue.

**Pull request merged**
